apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "bpfima.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: bpfima
  template:
    metadata:
      labels:
        app: bpfima
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bpfima.fullname" . }}
      hostPID: true
      initContainers:
        - name: bpfima-build-kernel-module
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            privileged: true
          volumeMounts:
            - name: host-modules
              mountPath: /host/lib/modules
            - name: host-src
              mountPath: /host/usr/src
            - name: host-lib
              mountPath: /host/usr/lib
              readOnly: true
          command: ["/opt/bpfima/scripts/init/build_kernel_module.sh"]
          args:
            - "{{ .Values.initKernelModule.tpm_pcr_index }}"
          {{- with .Values.initKernelModule.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        - name: bpfima-build-ebpf-programs
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: compiled-bpf-artifacts
              mountPath: /output
          command: ["/bin/sh", "-c"]
          args:
            - "cd /opt/bpfima && make bpf-only && cp -a build/* /output/"
          {{- with .Values.initEbpfPrograms.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      containers:
      - name: bpfima-tool
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: BPFIMA_PERSIST_STATE
          value: "1"
        securityContext:
          privileged: true
        volumeMounts:
          - name: compiled-bpf-artifacts
            mountPath: /bpf-programs
            readOnly: true
          - name: host-securityfs
            mountPath: /sys/kernel/security
          - name: host-policy-maps
            mountPath: /sys/fs/bpf
        command: ["/bin/sh", "-c"]
        args:
            - |
              cd /bpf-programs/ && \
              ./bpfima-tool load {{ join " " .Values.agent.bpfPrograms }} -d && \
              sleep infinity
        {{- with .Values.agent.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.agent.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      - name: bpfima-controller
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          privileged: true
        volumeMounts:
            - name: host-securityfs
              mountPath: /sys/kernel/security
            - name: host-policy-maps
              mountPath: /sys/fs/bpf
        command: ["/opt/bpfima-manager"]
        args:
        - --metrics-bind-address=:8080
        - --metrics-secure=false
        {{- with .Values.controller.readinessProbe }}
        readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        {{- with .Values.controller.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: compiled-bpf-artifacts
        emptyDir: {}
      - name: host-modules
        hostPath:
          path: /lib/modules
      - name: host-src
        hostPath:
          path: /usr/src
      - name: host-lib
        hostPath:
          path: /usr/lib/
      - name: host-securityfs
        hostPath:
          path: /sys/kernel/security
      - name: host-policy-maps
        hostPath:
          path: /sys/fs/bpf
      terminationGracePeriodSeconds: 0