apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: {{ include "bpfima.name" . }}
    app.kubernetes.io/component: controller-service-account
  name: {{ include "bpfima.fullname" . }}
