apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: bpfima
spec:
  selector:
    matchLabels:
      app: bpfima
  template:
    metadata:
      labels:
        app: bpfima
    spec:
      hostPID: true
      containers:
      - name: bpfima-v1
        image: iochia02/bpfima:v1.36
        securityContext:
          privileged: true
        volumeMounts:
        - name: host-modules
          mountPath: /host/lib/modules
        - name: host-src
          mountPath: /host/usr/src
        - name: host-lib
          mountPath: /host/usr/lib/
        - name: host-securityfs
          mountPath: /sys/kernel/security
        - name: host-policy-maps
          mountPath: /sys/fs/bpf
        - name: etc
          mountPath: /host/etc/
      volumes:
      - name: host-modules
        hostPath:
          path: /lib/modules
      - name: host-src
        hostPath:
          path: /usr/src
      - name: host-lib
        hostPath:
          path: /usr/lib/
      - name: host-securityfs
        hostPath:
          path: /sys/kernel/security
      - name: host-policy-maps
        hostPath:
          path: /sys/fs/bpf
      - name: etc
        hostPath:
          path: /etc/
      terminationGracePeriodSeconds: 0
      imagePullSecrets:
      - name: regcred
