apiVersion: v1
kind: Pod
metadata:
  name: bpfima
spec:
  containers:
  - name: bpfima-v1
    image: iochia02/bpfima:v1.1
    securityContext:
      privileged: true
    volumeMounts:
    - name: host-modules
      mountPath: /lib/modules
    - name: host-src
      mountPath: /usr/src
    - name: host-securityfs
      mountPath: /sys/kernel/security
    - name: host-policy-maps
      mountPath: /sys/fs/bpf
  volumes:
  - name: host-modules
    hostPath:
      path: /lib/modules
  - name: host-src
    hostPath:
      path: /usr/src
  - name: host-securityfs
    hostPath:
      path: /sys/kernel/security
  - name: host-policy-maps
    hostPath:
      path: /sys/fs/bpf
  terminationGracePeriodSeconds: 0
  imagePullSecrets:
  - name: regcred