# Default values for bpfima.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This sets the container image
image:
  repository: iochia02/bpfima
  # This sets the pull policy for images.
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v0.1"

# This sets the secrets for pulling an image from a private repository
imagePullSecrets: []
# This overrides the chart name.
nameOverride: ""
fullnameOverride: ""

# This sets the PCR to extend in the TPM and the resource limits/requests for the first init container
initKernelModule:
  tpm_pcr_index: 23
  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

# This sets the resource limits/requests for the second init container
initEbpfPrograms:
  resources: {}

# This sets up the readiness probe and the resource limits/requests for the container of the custom controller
controller:
  readinessProbe:
    httpGet:
      path: /readyz
      port: 8081
    periodSeconds: 1
  resources: {}


# This sets up the eBPF hooks to load, the readiness probe and the resource limits/requests for the container of bpfima-tool
agent:
  bpfPrograms:
    - lsm_bprm_check_security.o
    - lsm_socket_connect.o
    #- lsm_file_post_open.o
    #- lsm_inode_setattr.o
    #- lsm_mmap_file.o
  readinessProbe:
    exec:
      command:
        - cat
        - /var/run/bpfima.pid
    periodSeconds: 1
  resources: {}

# This ensures the DaemonSet is only scheduled on certain nodes
nodeSelector: {}

# This allows to bypass Kubernetes taints, ensuring that BPFIMA can monitor restricted or dedicated nodes on which standard workloads are normally not scheduled
tolerations: []
